SCALER_FILENAME = "scaler.gz"
MODEL_FILENAME = "classificator_model.cbm"
DATASET_FILENAME = "features_30_sec.csv"
MID_FILES_SUFFIX = ".mid"
WAV_FILES_SUFFIX = ".wav"
GENERATOR_MODEL_FILENAME = "model.pt"